#pragma config(UART_Usage, UART2, uartNotUsed, baudRate4800, IOPins, None, None)
#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    pb,             sensorNone)
#pragma config(Sensor, in2,    Gyro,           sensorGyro)
#pragma config(Sensor, in3,    G2,             sensorGyro)
#pragma config(Sensor, in4,    G3,             sensorGyro)
#pragma config(Sensor, in5,    AccX,           sensorAccelerometer)
#pragma config(Sensor, in6,    AccY,           sensorAccelerometer)
#pragma config(Sensor, dgtl1,  led,            sensorLEDtoVCC)
#pragma config(Sensor, dgtl2,  bottomT,        sensorTouch)
#pragma config(Sensor, dgtl3,  bottomL,        sensorTouch)
#pragma config(Sensor, I2C_1,  F1,             sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  F2,             sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           E,             tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           backLeft,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           frontLeft,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           backRight,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           frontRight,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           servo,         tmotorServoStandard, openLoop)
#pragma config(Motor,  port7,           F1,            tmotorVex393_MC29, openLoop, encoderPort, I2C_1)
#pragma config(Motor,  port8,           F2,            tmotorVex393_MC29, openLoop, encoderPort, I2C_2)
#pragma config(Motor,  port9,           A,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          A2,            tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(60)
#pragma userControlDuration(0)
#include "ShooterCode.h"
#include "Acquisition.h"
#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!



void pre_auton()
{
	bStopTasksBetweenModes = true;
	motor[servo]=0;
	wait1Msec(250);
	clearTimer(T1);

}



task autonomous()
{
	motor[servo]=0;
	startTask(FlywheelA);
	startTask(Acquisition);
	startTask(speedControlBottom);
	startTask(speedControlTop);
	startTask(LED);
	wait1Msec(500);
	while(true){
		if(speedSet==true&&speedSetB==true){
			TriggerA();
		}
	}
}

task usercontrol()
{

}
